export const ALL_CASES = [
  { image: "/images/cases/case-01.jpg", title: "令和2年度 垂坂1号線ほか1線 道路改良工事" },
  { image: "/images/cases/case-02.jpg", title: "令和2年度 東海環状北勢第二高架橋1下部工事" },
  { image: "/images/cases/case-03.jpg", title: "令和2年度 鈴鹿川下流部河道整備工事" },
  { image: "/images/cases/case-04.jpg", title: "令和2年度 鈴鹿川中流部河道整備工事" },
  { image: "/images/cases/case-05.jpg", title: "令和2年度 鈴鹿川河道掘削工事" },
  { image: "/images/cases/case-06.jpg", title: "令和2年度 長太雨水1-2号幹線 函渠布設工事" },
  { image: "/images/cases/case-07.jpg", title: "令和2年度 垂坂1号線ほか1線道路改良工事" },
  { image: "/images/cases/case-08.jpg", title: "令和3年度 吉崎地区海岸 海岸堤防等老朽化対策緊急工事" },
  { image: "/images/cases/case-09.jpg", title: "令和3年度 垂坂1号線ほか道路改良工事" },
  { image: "/images/cases/case-10.jpg", title: "令和3年度 木曽川源緑輪中高潮堤防嵩上工事" },
  { image: "/images/cases/case-11.jpg", title: "令和3年度 東海環状北勢地区道路建設工事" },
  { image: "/images/cases/case-12.jpg", title: "令和3年度 東海環状向平地区北部道路建設工事" },
  { image: "/images/cases/case-13.jpg", title: "令和3年度 鈴鹿川下流部掘削工事" },
  { image: "/images/cases/case-14.jpg", title: "令和3年度 長良川上坂手河道整備工事" },
  { image: "/images/cases/case-15.jpg", title: "令和4年度 1号伊勢大橋揖斐川右岸下部工事" },
  { image: "/images/cases/case-16.jpg", title: "令和4年度 北勢BP山之一色地区道路建設工事" },
  { image: "/images/cases/case-17.jpg", title: "令和4年度 一級河川足見川(左岸)ほか1川 令和4年河川災害復旧工事" },
  { image: "/images/cases/case-18.jpg", title: "令和4年度 南部浄化センター第2期事業導水渠建設工事その1" },
  { image: "/images/cases/case-19.jpg", title: "令和4年度 南部浄化センター第2期事業連絡管廊(土木)建設工事その3" },
  { image: "/images/cases/case-20.jpg", title: "令和4年度 吉崎地区海岸メンテナンス工事" },
  { image: "/images/cases/case-21.jpg", title: "令和4年度 揖斐川福吉高潮堤防嵩上工事" },
  { image: "/images/cases/case-22.jpg", title: "令和4年度 鈴鹿川維持修繕工事" },
  { image: "/images/cases/case-23.jpg", title: "令和5年度 南部浄化センター第2期事業場内整備工事その2" },
  { image: "/images/cases/case-24.jpg", title: "令和5年度 南部浄化センター第2期事業放流渠建設工事その5" },
  { image: "/images/cases/case-25.jpg", title: "令和5年度 木曽川福豊高潮堤防嵩上工事" },
  { image: "/images/cases/case-26.jpg", title: "令和5年度 東海環状塩崎地区建設工事" },
  { image: "/images/cases/case-27.jpg", title: "令和5年度 鈴鹿川河道掘削工事" },
  { image: "/images/cases/case-28.jpg", title: "令和5年度 塩浜雨水1号幹線水路構造" },
  { image: "/images/cases/case-29.jpg", title: "令和5年度 雨水路清掃業務委託(塩浜その2)" },
  { image: "/images/cases/case-30.jpg", title: "令和6年度 二級河川鹿化川 河川改修(治水対策)工事" },
  { image: "/images/cases/case-31.jpg", title: "令和6年度 塩浜雨水1号幹線水路築造工事" },
  { image: "/images/cases/case-32.jpg", title: "令和元年度 安楽川堤防補強工事" },
  { image: "/images/cases/case-33.jpg", title: "令和元年度 川島小学校法面整備工事" },
  { image: "/images/cases/case-34.jpg", title: "令和元年度 鈴鹿川南鹿島河道整備工事" },
  { image: "/images/cases/case-35.jpg", title: "令和元年度 鈴鹿川塩浜河道掘削工事" },
  { image: "/images/cases/case-36.jpg", title: "令和元年度 川崎白木線舗装工事" },
  { image: "/images/cases/case-37.jpg", title: "四日市市日永浄化センター第4系統建設工事その7" },
  { image: "/images/cases/case-38.jpg", title: "垂坂1号線ほか1線道路改良工事" },
  { image: "/images/cases/case-39.jpg", title: "平成26年度 鈴鹿川石原排水樋管撤去工事" },
  { image: "/images/cases/case-40.jpg", title: "平成27年度 23号御薗地区道路建設工事" },
  { image: "/images/cases/case-41.jpg", title: "平成27年度 南部浄化センター第2期建設事業農林堤防ほか堤脚水路嵩上工事" },
  { image: "/images/cases/case-42.jpg", title: "平成27年度 揖斐川地蔵下流川表高潮堤防補強工事" },
  { image: "/images/cases/case-43.jpg", title: "平成27年度 木曽川源緑防災ステーション基盤整備工事" },
  { image: "/images/cases/case-44.jpg", title: "平成27年度 東海環状高柳橋梁下部工事" },
  { image: "/images/cases/case-45.jpg", title: "平成27年度 鈴鹿川派川南五味塚築堤護岸工事" },
  { image: "/images/cases/case-46.jpg", title: "平成28年度 23号徳居南道路建設工事" },
  { image: "/images/cases/case-47.jpg", title: "平成28年度 木曽川鎌ヶ地上流川表高潮堤防補強工事" },
  { image: "/images/cases/case-48.jpg", title: "平成28年度 桜台1号線再舗装工事" },
  { image: "/images/cases/case-49.jpg", title: "平成28年度 西日野汚水管渠布設工事" },
  { image: "/images/cases/case-50.jpg", title: "平成28年度 鈴鹿川布気堤防法尻補強工事" },
  { image: "/images/cases/case-51.jpg", title: "平成28年度 鈴鹿川弓削地区上流部河道掘削工事" },
  { image: "/images/cases/case-52.jpg", title: "平成28年度 鈴鹿川派川北五味塚高潮堤防工事" },
  { image: "/images/cases/case-53.jpg", title: "平成28年度 長良川上坂手河道整備工事" },
  { image: "/images/cases/case-54.png", title: "平成29年度 一般国道477号四日市湯の山道路 道路改良(本線舗装)工事その3" },
  { image: "/images/cases/case-55.png", title: "平成29年度 鈴鹿川塩浜地区河道掘削工事" },
  { image: "/images/cases/case-56.png", title: "平成29年度 鈴鹿川塩浜河道掘削工事" },
  { image: "/images/cases/case-57.png", title: "平成29年度 鈴鹿川派川北五味塚高潮堤防工事" },
  { image: "/images/cases/case-58.jpg", title: "平成29年度 鈴鹿川甲斐災害復旧工事" },
  { image: "/images/cases/case-59.png", title: "平成30年度 鈴鹿川鈴鹿市上水道水管橋下部撤去工事" },
  { image: "/images/cases/case-60.jpg", title: "平成30年度 木曽川鎌ヶ地上流川表高潮堤防補強工事" },
  { image: "/images/cases/case-61.png", title: "平成30年度 桜西汚水管渠布設工事" },
  { image: "/images/cases/case-62.jpg", title: "平成30年度 鈴鹿川塩浜町河道掘削工事" },
  { image: "/images/cases/case-63.png", title: "平成30年度 鈴鹿川河道維持工事" },
  { image: "/images/cases/case-64.png", title: "平成30年度 鈴鹿川派川南部浄化センター排水樋管改築工事" },
  { image: "/images/cases/case-65.png", title: "平成30年度 北勢BP田光四日市跨道橋下部工事" },
  { image: "/images/cases/case-66.jpg", title: "平成31年度 主要地方道上海老茂福線舗装修繕工事(その2)" },
  { image: "/images/cases/case-67.jpg", title: "平成31年度 主要地方道四日市楠鈴鹿線 地域維持型修繕(歩道修繕)工事" },
  { image: "/images/cases/case-68.png", title: "羽津鵤25号線ほか1線舗装修繕工事" },
];
